### ISSUE TITLE
How to apply a StyleSheet to the whole app?

### ISSUE THREAD

**Issue by Carl-Hugo** [xamarin/MobileBlazorBindings#117]
Background: I'm not a seasoned Xamarin developer, so I have to discover Xamarin at the same time.

I was playing around with the MobileBlazorBindings and built a small UI based on a `<Shell>` so I have a menu, nav, etc. Here is a simplified repro page (`StandAloneShell.razor`):

```xml
<Shell>
    <FlyoutHeader>
        <StackLayout>
            <Label Text="Some cool title!" class="app-menu-header" />
        </StackLayout>
    </FlyoutHeader>
    <ChildContent>
        <ShellContent Route="home" Title="Home">
            <ContentPage>
                <StackLayout>
                    <Label Text="This is the Home page!" />
                </StackLayout>
            </ContentPage>
        </ShellContent>
        <ShellContent Route="empty" Title="Empty">
            <ContentPage>
                <StackLayout>
                    <Label Text="This is an Empty page!" />
                </StackLayout>
            </ContentPage>
        </ShellContent>
        <ShellContent Route="page2" Title="Page 2">
            <ContentPage>
                <StackLayout>
                    <Label Text="This is Page 2!" />
                </StackLayout>
            </ContentPage>
        </ShellContent>
    </ChildContent>
</Shell>
```

I load the `App` like this: `_host.AddComponent<StandAloneShell>(parent: this);`

I'm trying to load a `.css` file to skin my `StackLayout > Label`, but I can't figure out how.

I tried to load `<StyleSheet Resource="App.css" Assembly="GetType().Assembly" />` (both on an Android emulator or my android phone):

1. Over the `<Shell>` element (boom!)
1. Inside the `<Shell>` element (boom!)
1. Inside  the `<FlyoutHeader>` element (nothing happens) 
1. Inside a `<ContentPage>` (it works only for the content of that page, but not for the `<FlyoutHeader>`)
1. Move the `<Shell>` into a `<ContentPage>` (boom!)
1. Most likely in other places, but I'm a bit desperate now 😉 

So is that possible? 
- If so, how? 
- If not, why? Can I implement a workaround? Should I wait for something? Can I help make that happen?

Thanks in advance

---

## My general opinion so far

While at it, I read somewhere that you want opinions, so here is my opinion so far: many tasks that I believed would be trivial became quests (and Google searches). The Hot Reload doesn't seem to be reloading anything, which makes the process very tedious and lengthy. That said, this approach sounds promising for those like me who don't like XAML (I never got that move to XAML), but it is still pretty-XAML-y without the ugly bindings. 

All in all, keep up that excellent work, and maybe one day Razor will be the universal view engine unifying all MSFT's techs... 🍻

**Comment by Eilon** [comment]
Hi, sorry you had a problem with loading CSS. I've seen another report of problems using CSS at #104 when the `<StyleSheet>` element is placed in certain locations, but that it works in other locations. Perhaps there is a hint in that issue that would help you? I still need to investigate it myself some more to understand why it only works in some places, or at least why there isn't a better error when it doesn't.

And for your other feedback:

* This is an experimental project so I thank you for all your feedback! That's exactly why we're doing this experiment. Unfortunately that means that some areas are not well-supported or well-documented, but I'd like to help you out so we can get even more feedback. Please let me know how I can do that.
* Indeed, Hot Reload is not supported. It's one of the areas that we plan to have some support for but right now that's a very complex area. As far as I know, right now Hot Reload is for XAML-basic solutions only, so that's why it doesn't work here.
* And also thank you for the kind words! We'd love for Blazor to have far reach and this project is helping us figure out how to make it work for developers like you!

**Comment by Carl-Hugo** [comment]
@Eilon I started to search for issues, found #104, read it, then created this one.

I open-sourced my experimental/weekend project if that can help you: https://github.com/Carl-Hugo/BlazorMobileExperiments

The [StandAloneShell.razor](https://github.com/Carl-Hugo/BlazorMobileExperiments/blob/master/src/Core/Pages/StandAloneShell.razor) page is the code I added here while [ShellPage.razor](https://github.com/Carl-Hugo/BlazorMobileExperiments/blob/master/src/Core/Pages/ShellPage.razor) is the real page that I want to add CSS to. At the moment, the [App.css](https://github.com/Carl-Hugo/BlazorMobileExperiments/blob/master/src/Core/App.css) file is not loaded anywhere since I was not able to figure it out, abandoned, and opened this issue. To load the dumbed-down version, just change the `_host.AddComponent<...>(...)` in [App.cs#L36](https://github.com/Carl-Hugo/BlazorMobileExperiments/blob/master/src/Core/App.cs#L36).

Please let me know if I can help and how.

Side note: it is funny (but very unimportant) that VS displays "Hot Reload enabled" or something like that when it's not... 🍻

**Comment by Eilon** [comment]
Hi @Carl-Hugo , it's been a little while but I think I have your scenario fully working now!

There are a few things I did to get it working:

1. I am using the [nightly feed of Mobile Blazor Bindings](https://review.docs.microsoft.com/en-us/mobile-blazor-bindings/contribute/nightly-builds?branch=master) to get the latest fixes related to CSS
1. As part of this, I updated to use both the latest Mobile Blazor Bindings, and also the latest Xamarin.Forms
1. I added a reference to the CSS file from within the Shell control's Contents section as seen in this PR that I sent to your project repo: https://github.com/Carl-Hugo/BlazorMobileExperiments/pull/3
1. I changed your project to use a slightly newer startup pattern to avoid various errors on various platforms. This is done using a Blazor-specific host instead of using the default generic host in app startup.

As far as I know, all the CSS is working in your app now. As such, I am closing this issue. But if you find anything else that isn't working as you expect, or if you have any other feedback, please let me know!

**Comment by Carl-Hugo** [comment]
Thanks for looking into this. I left you a few comments in the PR since it's easier to comment right in the code.

That said, I don't have access to the [nightly feed of Mobile Blazor Bindings](https://review.docs.microsoft.com/en-us/mobile-blazor-bindings/contribute/nightly-builds?branch=master):
![image](https://user-images.githubusercontent.com/5885505/90774121-f29c0500-e2c4-11ea-9c33-2e289359da25.png)

**Comment by Eilon** [comment]
Oops, here's the link for info on the nightly feed: https://docs.microsoft.com/mobile-blazor-bindings/contribute/nightly-builds

**Comment by Eilon** [comment]
And I responded to your comments in https://github.com/Carl-Hugo/BlazorMobileExperiments/pull/3.

**Comment by Carl-Hugo** [comment]
I loaded the project, added the `nuget.config` file, and it worked like a charm: the `Label.app-menu-header` is `aqua` yeah! 

*OK, I sound a little too excited about an aqua label but hey global CSS works now* 😉 

That said, I'm not sure that I like the pseudo-CSS of Xamarin, but that's another story. The important part is that it is working. 

Thanks again, keep up the good work, this project shows a promising future IMHO; I'd so like to see more Razor and less XAML in the future, this project gives me hope (not that I think MSFT will drop XAML anytime soon, but a guy can dream)

**Comment by Eilon** [comment]
@Carl-Hugo thank you again for trying out this project and sharing your feedback. I love using Razor to build all my UI so I am very motivated to make this experience as wonderful as possible!
