### ISSUE TITLE
How to use Mobile Blazor Bindings with pure C# code?

### ISSUE THREAD

**Issue by evolcano** [xamarin/MobileBlazorBindings#143]
First, thanks all you guys to bring MobileBlazorBindings to reality! It's a huge leap. And it is the most exciting news in this week for me.

But I'm a bit of confusing about the example:
```
<StackLayout>
    <Label FontSize="30"
           Text="@("You pressed " + count + " times")" />
    <Button Text="+1"
            OnClick="@HandleClick" />
</StackLayout>

@code {
    int count;

    void HandleClick()
    {
        count++;
    }
}
```
 
I have many code base on Xamarin. The example is very different from the ordinary way which we build Xamarin cross platfrom APP. I wish the example could be coded as something like this:
```
public class Example : ContentPage
{
    public Example()
    {
        StackLayout layout = new StackLayout();
        this.Content = layout;

        layout.Children.Add(new Label()
        {
            FontSize = 30,
            Text = "@("You pressed " + count + " times")"
        });
        Button but = new Button()
        {
            Text = "+1"
        };
        but.Clicked += But_Clicked;
        layout.Children.Add(but);
    }

    int count;

    private void But_Clicked(object sender, EventArgs e)
    {
        count++;
    }
}
```

If Blazor could bind like this as Android ,iOS and UWP did, I could reuse many existed code directly. And I think this is REAL Xamarin binding, and not Xamarin UI integrating.
I think the important reason to make any new technology shine is to make the Eco-system stronger in a consist way. 
Why couldn't use Blazor as a new Platform target from the very beginning? Maybe MAUI could achieve this, but I can't wait!

Did I mixed something up? Or miss understood something?

**Comment by lachlanwgordon** [comment]
@evolcano I think what you're after is kind of the opposite of Mobile Blazor Bindings. Or maybe I misunderstood your question.

Mobile Blazor Bindings(can we abreviate that to MBB) lets your write a Xamarin Forms app using Razor Syntax that will run on the usual XF platforms(iOS,Android UWP, etc.). It's an alternative to writing in XAML or a coded UI mainly targetted at helping people who have experience with Blazor write native mobile apps.

If you want to be able to run the Xamarin Forms code that you're used to writing(either XAML or C# markup) and have it run on the web there are a couple of options. [Frank Kruegers Ooui](http://ooui.mecha.parts/) lets you write web UIs using Xamarin Forms and [Uno Platform](https://platform.uno/) lets you wrap up any UWP app(including UWP written in XF) and run it on the web. Netiher of them are official but both are really cool.

My understanding is that MAUI won't offer a web target at launch time but it will make it easier for a web based version to happen in the future, but I'd guess that's a few years off, but I really want it.

Regarding your original question of how to use MBB with pure C# code. I think theoretically the answer is yes, but all that it would achieve is an app that runs on the usual Xamarin Forms platform, but your code would be far more complicated compared to writing your UI in C# without MBB.

You could potentially put an MBB app inside UNO or Ooui. Interesting as that may be, probably not what you're after.

**Comment by Eilon** [comment]
+1 to what @lachlanwgordon stated.

It's perhaps worth noting that you _can_ use all of Blazor from code, because all Blazor markup gets compiled into code. Blazor markup is not used at runtime. Everything turns into C# when you compile your app, then only C# runs (well, MSIL, really). So, if you want, you can hand-write all the generated Blazor code. But, then you lose all the value of Blazor!

To see what Blazor generates from the `.razor` markup, go to any Blazor app, then look for files like this on disk `<PROJECT>\obj\Debug\netstandard2.0\Razor\<FILENAME>.razor.g.cs`. But really, you don't want to hand-write that code.

Blazor's real value (for me, certainly), is in how it mixes C# and markup in a natural and appealing way. If you want a C#-based app, then Xamarin.Forms (and soon, .NET MAUI), already have great ways of doing that.
