### ISSUE TITLE
Skia Sharp Mobile Blazor Bindings

### ISSUE THREAD

**Issue by lachlanwgordon** [xamarin/MobileBlazorBindings#167]
This is the new home for the issue [1455](https://github.com/mono/SkiaSharp/issues/1455) in the Skia Sharp repo. After some discussion over there it sounds like it fits best here for now.

I'm working on a wrapping project to use SkiaSharp in Mobile Blazor Binding. 

I'm thinking it's best to build it in the SkiaSharp namespace, even though it lives here to make it feel similar to using SkiaSharp on other platforms. Unless someone objects? It's not a big deal to change it if I get it wrong.

The scope of this issue will be limited to using SkiaSharp in Mobile Blazor Bindings Native. Hybrib app Skia will also be interesting but we'll leave that for another day.

Using the SKCanvas will look like this:

```
<ContentPage>
    <StackLayout>
        <SKCanvasView InvalidateSurface="@PaintSurface"></SKCanvasView>
    </StackLayout>
</ContentPage>

@code 
{ 

    void PaintSurface (object sender, SkiaSharp.Views.Forms.SKPaintSurfaceEventArgs e)
    {
        var surface = e.Surface;
        var canvas = surface.Canvas;
        canvas.Clear(SkiaSharp.SKColor.Parse("#CC0000"));
    }
}
```

**Comment by Eilon** [comment]
I dig it!

As far as namespace goes, I suggest that the namespace match the "environment" (i.e. the GitHub repo) that contains the code. For example, the [Pancake view sample wrapper](https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/MobileBlazorBindingsWeather/Microsoft.MobileBlazorBindings.PancakeView) is in the Microsoft.MobileBlazorBindings.* assembly/namespace.

I think this is important because when it comes to NuGet packages (which this obviously will be), the `Microsoft.MobileBlazorBindings.*` _package_ namespace is reserved on NuGet.org for MBB only, meaning that no one else can "squat" any names. I think it also makes it clearer at a glance as to who "owns" the code. Is this Microsoft Mobile Blazor Binding's wrapper for SkiaSharp? Or is it SkiaSharp's integration with Mobile Blazor Bindings? The code might be essentially the same, but it's subtly different in terms of how someone looking at it for the first time might see it.

Thoughts?

**Comment by mattleibow** [comment]
I am just thinking that maybe this will change in the future? For example, it might be an autogenerated way to do this whole connection. What are the chances that the IDE/tooling might have a task that would scan all referenced assemblies and "generate" the wrappers for MBB? This might also be great for all users for all libraries. Then, the actual control might not exist in this source.

Am I making sense?

Basically, I see some of this code is already generated, so could this move into a MSBuild target and run on the build? If I want to use library X with view Y, then it will be generated once-off in the obj folder and then I can use it from there? Since I have already been working with my hands in MSBuild tasks for years now, I could help out with this. A seamless integration of "any" XF library - at least for the native bindings part. Not sure about the hybrid atm.

**Comment by Eilon** [comment]
@mattleibow that would be super nice - it's an area I'm looking into as well. But I don't know if/when that will land.

**Comment by mattleibow** [comment]
Awesome! Let me know if you want to chat. Do we have a specific issue for this?

**Comment by Eilon** [comment]
Yup #151 !

**Comment by RChrisCoble** [comment]
@Eilon @lachlanwgordon This is the XAML syntax with MBB, will this also work with the razor syntax?  By that I mean, the UI is run in the thin browser shim using MBB but SkiaSharp works as expected on the device like you have here?

**Comment by lachlanwgordon** [comment]
The snippet above is Razor Syntax(not xaml), but it uses the Xamarin Forms controls to make a native mobile/desktop App with skia sharp in it.

If you're wanting to use SkiaSharp in a Blazor web site, that's a different issue which Mobile Blazor Bindings can't help you with. 

SkiaSharp in Blazor Web is being discussed here https://github.com/mono/SkiaSharp/issues/1194, it looks like you're already involved over there.

If you want more info on how to use this feature feature in a Mobile Blazor Bindings app, the docs are here. https://github.com/MicrosoftDocs/mobile-blazor-bindings/blob/master/mobile-blazor-bindings/walkthroughs/skiasharp.md

They're not published to the microsoft docs site yet because this is part of Preview 5 which hasn't been released yet, but you can read the docs on github and use the [Nightly Builds](https://docs.microsoft.com/en-us/mobile-blazor-bindings/contribute/nightly-builds) now.

**Comment by Eilon** [comment]
Thank you @lachlanwgordon for answering!

@RChrisCoble if you have another scenario in mind please let us know!

**Comment by RChrisCoble** [comment]
> The snippet above is Razor Syntax(not xaml), but it uses the Xamarin Forms controls to make a native mobile/desktop App with skia sharp in it.
> 
> If you're wanting to use SkiaSharp in a Blazor web site, that's a different issue which Mobile Blazor Bindings can't help you with.
> 
> SkiaSharp in Blazor Web is being discussed here [mono/SkiaSharp#1194](https://github.com/mono/SkiaSharp/issues/1194), it looks like you're already involved over there.
> 
> If you want more info on how to use this feature feature in a Mobile Blazor Bindings app, the docs are here. https://github.com/MicrosoftDocs/mobile-blazor-bindings/blob/master/mobile-blazor-bindings/walkthroughs/skiasharp.md
> 
> They're not published to the microsoft docs site yet because this is part of Preview 5 which hasn't been released yet, but you can read the docs on github and use the [Nightly Builds](https://docs.microsoft.com/en-us/mobile-blazor-bindings/contribute/nightly-builds) now.

@lachlanwgordon Thanks for the correction.  I've spoken at length with @mattleibow who owns the SkiaSharp repo and to get SkiaSharp going on WASM he needs the upcoming .Net 6 AOT feature support which hopefully will drop in preview releases sometime in Q1/Q2 so he can get started.  AOT appears to be the top requested feature in the .Net 6 roadmap.

I'm assuming this means for code to draw with SkiaSharp in the browser client the code itself also has to be compiled/linked to a .wasm target directly (like Uno is doing), making it specific to the web context.  For the same code to execute on multiple devices (not web) with SkiaSharp, what you've done appears to be the path forward. 

Keep up the great work!  👍
