### ISSUE TITLE
[Bug] Exceptions are swallowed in VS when using Nuget package

### ISSUE THREAD

**Issue by mgrman** [xamarin/MobileBlazorBindings#171]
Exceptions are swallowed in VS when using Nuget package, e.g. missing service to be injected in Blazor page.

**Reproduction steps:**
1. Create new project based on template ( [Last blog article](https://devblogs.microsoft.com/aspnet/hybrid-blazor-apps-in-mobile-blazor-bindings-july-update/) )
2. `dotnet new -i Microsoft.MobileBlazorBindings.Templates::0.4.74-preview`
3. `dotnet new blazorhybrid -o MyHybridApp`
4. In **MyHybridApp\App.cs** remove line  **services.AddSingleton<CounterState>();** to simulate that a service is missing from DI.
5. Start the **MyHybridApp.Windows** application in VS

**Expected result:**
VS breaks code execution and shows or at least logs the exception with StackTrace.

**Current result:**
No exception is logged, not visible indication of Error and the Blazor part of the app does not start (remains white).

**Notes:**
When I try the same change in the sample included in cloned repo, I get exception in NativeComponentRenderer. Not sure if they get swallowed or not. 
This makes is very hard to try out exising Blazor projects with MobileBindings. Since there are some services still missing like https://github.com/xamarin/MobileBlazorBindings/issues/150

**Comment by Eilon** [comment]
Hi @mgrman thank you for the report, we'll have a look and try to figure out what's going on here. A mis-configured app should probably end with some fatal exception instead of hiding it.

**Comment by Eilon** [comment]
OK I have a new near-term strategy for handling fatal errors in Mobile Blazor Bindings apps:

All fatal errors (that is, something that would end up killing the app) will show the Mobile Blazor Bindings full-screen error page. This includes these types of exceptions:

1. Exceptions while creating a component (such as the app's main UI). This includes the type of exception originally reported in this bug where a required service was not available from DI so the component couldn't be created.
1. Exceptions during rendering/running native UI.
1. Exceptions during rendering/running web UI (such as in a hybrid app).

I say near-term because right now this exception page will be shown even in a production app, which is clearly something no one would want. But this is an experimental project so I figure it's better to have the errors in-your-face instead of crashing the app. Also, I don't know the best way to "crash" the app in a traditional way, so there's that.

I think eventually maybe this will become a service that will be in the host's DI container and can be different in debug/release mode.
