### ISSUE TITLE
[Question] How to handle OnNewIntent() in WebUI project

### ISSUE THREAD

**Issue by ktaze1** [xamarin/MobileBlazorBindings#191]
## Background and Description

I was following [this tutorial][1] from Microsoft for adding notifications to my mobile app. The app I'm building is just a webui.

MyApp/Main.razor:
```
<ContentView>
    <StackLayout>
        <BlazorWebView ContentRoot="WebUI/wwwroot" VerticalOptions="LayoutOptions.FillAndExpand">
            <MyApp.WebUI.App />
        </BlazorWebView>

    </StackLayout>
</ContentView>
```

After setting up project in Firebase and notification hub in Azure I was implementing the Xamarin Forms functionality and had an error.

[Here in this code snippet][2] it overrides onNewIntent:

```
protected override void OnNewIntent(Intent intent)
    {
        if (intent.Extras != null)
        {
            var message = intent.GetStringExtra("message");
            (App.Current.MainPage as MainPage)?.AddMessage(message);
        }

        base.OnNewIntent(intent);
    }
```

## Problem

`MainPage` in `(App.Current.MainPage as MainPage)?.AddMessage(message);` is the name of the xaml file in shared client project in the example Xamarin Forms Project. However in my project after changing `MainPage` to `MyApp.Main` I am getting this error:

`Cannot convert type 'Xamarin.Forms.Page' to 'MyApp.Main' via a reference conversion, boxing conversion, unboxing conversion, wrapping conversion, or null type conversion`

My understanding is that I should point to my main page, so after I click to notification that event should add the message to my main page. Since I don't use xaml files I tried to point my entry point (not the `App.cs` but `Main.razor`) How should I proceed from here?

I believe I can use the notifications with WebUI, can't I? Any thoughts on this?

  [1]: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub
  [2]: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub#add-incoming-notifications-to-the-xamarinforms-ui

**Comment by Eilon** [comment]
Hi @ktaze1 can you show more of the code that you have? Or upload your whole project as a GitHub repo?

What is the base class of `MyApp.Main` in your project? I'm guessing that it's the compiled Blazor page, in which case it won't derive from `Xamarin.Forms.Page`, so the code won't compile.

I've written up a small and simple sample that shows a more Blazor-oriented way to write this type of pattern.

The repo is here: https://github.com/Eilon/AddMessageNotificationSample

But to see the relevant changes for this, just look at this particular commit: https://github.com/Eilon/AddMessageNotificationSample/commit/fab66fd31bbbba8a13bf524f5c9e65a38c8d78dc

And then this is the `SendMessageToMainPage` method that you'd use whenever your app needs to "receive" a message and show it somewhere: https://github.com/Eilon/AddMessageNotificationSample/blob/main/AddMessageNotificationSample/App.cs#L28-L34

This particular sample shows using native UI, but the exact same pattern works with Web UI as well. You would remove the `MessageList.razor` that I show in this sample and instead do that in WebUI using HTML, but everything else should be the exact same in terms of AppState and change notifications.

I'm closing this issue because I think it covers everything, but feel free to let me know if you have any further questions. Thanks!
