### ISSUE TITLE
Any plans for Blazor Server style operation?

### ISSUE THREAD

**Issue by dsedmak** [xamarin/MobileBlazorBindings#206]
The Readme states:
> In hybrid apps you can embed Blazor web UI directly in the app in any composition, all running in the same app process. No web servers.

A lot of applications still need to communicate with the server on almost every meaningful interaction.
For such applications a Blazor Server style operation would be preferable because there's no need for an API...
This means the code behind executes on the server.

In hybrid apps this should be possible since it's just a website so the question also covers native apps made with blazor bindings.

Are there any plans for this? Was it brought up before or discussed?

**Comment by Eilon** [comment]
Hi @dsedmak this is essentially already possible today: Use a regular WebView and point it at `https://myapp.example.com/` and using some JavaScript interop you can communicate between the server app that is rendering in the WebView and the rest of the native app.

It's not a scenario that we plan to invest much effort into because you can already do it today. Also, I don't think many apps would choose this experience because it has almost no benefits of a native/hybrid app and many of the disadvantages of a pure web app. That is, it won't run without a network connection even to display some basic UI.

**Comment by dsedmak** [comment]
I am aware that you can do this by running a PWA in a WebView.
That also covers the basic UI when you're offline.

That is why I was asking about native apps with blazor bindings.
You could have native looking iOS and Android apps and save some work on the API, the double validation...
It really depends on the use case whether the app should work offline. Apps centered around collaboration would have to be online.

But I have my answer regardless. Thank  you. You can close the issue now.

**Comment by Eilon** [comment]
If you have any thoughts on what specific features or functionality we could add that could make this easier, that's certainly worth discussing, so please let us know!
