### ISSUE TITLE
MenuItems are added to Shell in wrong order

### ISSUE THREAD

**Issue by Dreamescaper** [xamarin/MobileBlazorBindings#220]
AppShell.razor
```razor
<Shell>
    <FlyoutItem Title="Tab1">
        <Tab Title="Tab2">
            <ContentPage />
        </Tab>
    </FlyoutItem>
    <FlyoutItem Title="Tab2">
        <Tab Title="Tab1">
            <ContentPage />
        </Tab>
    </FlyoutItem>

    <MenuItem Text="Menu1"></MenuItem>
    <MenuItem Text="Menu2"></MenuItem>
    <MenuItem Text="Menu3"></MenuItem>
</Shell>
```

Result:
![image](https://user-images.githubusercontent.com/17177729/98302601-5d580500-1fc5-11eb-846a-d6c08fceac52.png)

**Comment by Dreamescaper** [comment]
Problem is in `ElementHandler.GetPhysicalSiblingIndex`:

https://github.com/xamarin/MobileBlazorBindings/blob/aa6112e7fae894ebc2f1e0fb1bb2cc6f5bd342ee/src/Microsoft.MobileBlazorBindings/Elements/Handlers/ElementHandler.cs#L142-L146

Because of implicit conversion from _MenuItem_ to _ShellMenuItem_, our _menuItem_ is not in the _parentAsShell.Items_. Instead, _Items_ contains _ShellMenuItem_, which wraps our _menuItem_.
(Even though menuItem's Parent **is** _parentAsShell_!)

**Comment by Eilon** [comment]
Oh nice catch! Definitely a bug.

**Comment by Dreamescaper** [comment]
I would suggest to refactor it (after #219 is merged), and to add method `GetChildIndex` to `IXamarinFormsContainerElementHandler` interface. This each parent handles own childred instead of having huge method handling every possible parent.

And it would allow to use same code already implemented in #219 . Cause we have same ShellMenuItem issue here, I'd like to avoid having reflection calls here as well.

**Comment by Eilon** [comment]
Yeah that sounds good. I'm running into an issue in my tests that might be a Xamarin.Forms issue so I'll have to look closer. I'm dynamically adding all kinds of Shell-related items and with some of them something isn't too happy:

![image](https://user-images.githubusercontent.com/202643/98731150-2598e680-2352-11eb-9c7a-30ef03218a40.png)

**Comment by Eilon** [comment]
This might be because Blazor creates things outside-in, one at a time, and parents them to their containers. So it creates a new ShellContent (which is empty), adds it to the parent Tab, and then adds the children to the empty ShellContent. But Xamarin.Forms doesn't like an empty ShellContent.

Assuming this is the case, we've had this issue before with DummyShellItem where a temporary item was added to the control to avoid failing the check, and when the first "real" child was added, the temporary item was removed. Perhaps we need that here?
