### ISSUE TITLE
Simple Animations in MBB

### ISSUE THREAD

**Issue by cornem** [xamarin/MobileBlazorBindings#236]
The [ViewExtensions](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/animation/simple) class provides extension methods that can be used to construct simple animations. However, this doesn't seem to work with MBB components. Is there any way to make this work ATM, or guidance on how it could be made to work?

**Comment by Eilon** [comment]
Actually, you should be able to use those! Because they work on the Xamarin.Forms controls and not the Blazor components, you'll need to [access native controls](https://docs.microsoft.com/en-us/mobile-blazor-bindings/advanced/access-native-controls). Once you have the native control (such as `Xamarin.Forms.Image`), you should be able to use any of those extensions.
