### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by Dreamescaper** [xamarin/MobileBlazorBindings#284]
Would be great to add editorconfig file to enforce single code style across code base (and to enforce license headers).

Maybe it could be expanded later by adding and configuring StyleCop.

**Comment by Dreamescaper** [comment]
Also, would it be possible to make Azure DevOps builds for PRs public?
I can often see that build is failed for my PRs, but can't even see why.

**Comment by Eilon** [comment]
There is this file: https://github.com/xamarin/MobileBlazorBindings/blob/master/.editorconfig

Is it incomplete? If so I'd be happy to have more stuff enabled there to make working on the project easier.

For DevOps public builds: I _thought_ I had that working at one point but it's clearly not anymore. I did at least fix it so that the non-public builds at least correctly reports success/failure (instead of always failing). I think you can see some errors but not all of them, and you can't see the detailed logs.

I will spend more time on this to see what's going on.

**Comment by Dreamescaper** [comment]
Ooooops))
Missed that file, not sure why :)

Still would be great to configure it, e.g. add MIT license header.
I noticed that you've added braces for single line 'if' statements, would make sense to set severity to 'warning' instead of 'silent', if I understand that correctly.

Maybe I could submit PR later to make it more strict for further discussion.


As for DevOps builds - I cannot access build details at all, so I only know whether it's passed or failed.

**Comment by Eilon** [comment]
EditorConfig: Yes if there are any things that are silent that shouldn't be, feel free to fix! I don't remember how I made the file. Perhaps VS generated it with some "reasonable" defaults?

DevOps builds: I see this in one recent PR:
![image](https://user-images.githubusercontent.com/202643/103700901-008fb100-4f5a-11eb-9efe-c1de90ba3f21.png)

But I think to go deeper into the logs you need to have internal access. I think it's better than _nothing_, but clearly it's not super great.

**Comment by Dreamescaper** [comment]
Again, my bad. 
I simply tried to click Details link on the bottom of the page.
![image](https://user-images.githubusercontent.com/17177729/103701183-3c546600-4fae-11eb-82ba-12eaf3a51d34.png)


Yeah, it's actually should be enough in most cases, I missed that.

**Comment by Dreamescaper** [comment]
Anyway, closing this item, as editorconfig file is already present.

**Comment by Eilon** [comment]
No worries, I didn't even realize it myself until I clicked it by accident a while ago! It's odd that each way to get to the info gives slightly different stuff 😄
