### ISSUE TITLE
Hello World issues

### ISSUE THREAD

**Issue by tleylan** [xamarin/MobileBlazorBindings#38]
First this is all amazing, thanks. I've tried a few times now and various different things happen but while the app starts in the emulator I never see any text.

The template seems to have set the project to Android 9.0. I thought I read it needed 8.0. Perhaps it simply chose the latest version on my machine or am I am mistaken? I set the emulator to 8.0 but it didn't display when I set it to 9.0 either.

There was an issue re: namespace collisions for Button, Label and others. I managed to resolve them but I figured it should compile and run without error so again something must be up with my installation. It is using Xamarin.Forms 4.3.0.908675 which again I think I need. Will it work if I get latest stable?

Assistance would be appreciated. Thanks.

**Comment by tleylan** [comment]
uhhh.... never mind :-) I don't what happened the first couple of times but this time it all worked and I have a phone app. Still wouldn't mind knowing about any library version restrictions if there are any.

**Comment by Eilon** [comment]
Hi @tleylan , I figured I'd reply even though this is already closed. The basic requirements are the same as a regular Xamarin.Forms project, because Xamarin.Forms is what's doing all the heavy lifting in terms of interacting with Android and iOS. So, you'll see various settings and configuration options within the `.Android` and `.iOS` projects that are created in the solution.

You can read more about Xamarin.Forms minimum requirements here: https://docs.microsoft.com/en-us/xamarin/get-started/requirements?tabs=windows

**Comment by tleylan** [comment]
Hi @Eilon. Good to know I've updated my project to the latest Android version and it seems to work. The major issue I had with Hello World was VS 2019 was displaying all sorts of errors. Cloned it a third time and everything settled down. I got rid of the namespace collisions by using an alias on the Xamarin namespace. As always thank you for your follow ups.

**Comment by Eilon** [comment]
Hi @tleylan yeah the namespace collision thing is quite annoying and I'm investigating it. You can track that here: https://github.com/xamarin/MobileBlazorBindings/issues/49 . Using aliases is a nice workaround, although of course quite tedious. Those errors are fortunately all innocuous so you can ignore them. But _gosh_ they are annoying! 😄
