### ISSUE TITLE
Blazor syntax mismatch

### ISSUE THREAD

**Issue by kevinjpetersen** [xamarin/MobileBlazorBindings#40]
First of, amazing experiment that just started. I'm definitely gonna use, test and help out where I can with this!

Now, onto my "issue" or rather a thing I fell over looking at the syntax in Mobile Blazor Bindings vs normal "Blazor" for ASP.NET Core.

While regular Blazor uses the pattern like for example: `@onclick="HelloWorldFunction"`, Mobile Blazor Bindings uses the old way through `onclick="@HelloWorldFunction"`, the difference ofcoruse being where the `@`- sign is located.

Are there any plans to change the **syntax** to be identical with regular ASP.NET Core / WebAssembly Blazor?

**Comment by Eilon** [comment]
It's based on the same syntax because it's the same parser (there's only 1 parser, and it's Razor). But I'll need to hear from @SteveSandersonMS / @rynowak / @ntaylormullen to see if they might know why specifying event handlers is different.

**Comment by Kahbazi** [comment]
I'm guessing it's ok the way it is. In web a button tag is not a blazor component so there's no `onclick` parameter so I think it needs `@` to say this is a C# code but in mobile, button is a blazor component and it has an `OnClick` parameter, so there's no need for `@`. You can even write `onclick="HelloWorldFunction"` for mobile.

**Comment by SteveSandersonMS** [comment]
@Kahbazi You're correct.

We wanted to retain compatibility with plain HTML, which means that `<button onclick="something">` has to treat `something` as a JavaScript expression to be invoked, as it always has done in HTML. That's why we need a different syntax (`@onclick`) if you want to invoke C# when clicking on an HTML element.

For a Blazor component, parameter names are arbitrary and we don't need to distinguish event handler parameters from any other parameters.

**Comment by Eilon** [comment]
Closing because this is answered. Great question!
