### ISSUE TITLE
Extending the Mobile Elements

### ISSUE THREAD

**Issue by rlebowitz** [xamarin/MobileBlazorBindings#53]
The project looks quite promising; I'm hoping that it is eventually made part of an official API.  

After looking at the source code for the various elements I realized that only a few of the many properties for the Xamarin.Forms elements are exposed, and due to the fact that the underlying native control is not itself exposed as a Blazor parameter, there is no way to set those properties.  

In my case I was attempting to use the FlowDirection property to use RTL functionality (I work on some Hebrew language apps from time to time).  

I suppose I could write my own components and expose the FlowDirection property as a parameter myself, but I wonder if there is a "better" way to do this.

BTW, I noticed that someone else complained about the error messages indicating ambiguity between the mobile blazor binding elements and the Xamarin Forms ones.  I simply substituted the line @using XF = Xamarin.Forms in _Imports.razor for the @using Xamarin.Forms and then applied the prefix XF. to those items that derive from the forms classes.  It's not a "perfect" solution, but it eliminated the error messages and didn't require a lot of extra text in the razor files.  I found that I could specify the @code{} segment of my files in partial classes to better separate the UI and logic using this technique quite easily.

**Comment by 0x414c49** [comment]
> BTW, I noticed that someone else complained about the error messages indicating ambiguity between the mobile blazor binding elements and the Xamarin Forms ones. I simply substituted the line @using XF = Xamarin.Forms in _Imports.razor for the @using Xamarin.Forms and then applied the prefix XF. to those items that derive from the forms classes. It's not a "perfect" solution, but it eliminated the error messages and didn't require a lot of extra text in the razor files.

Could you mention this in this #49 as well? It's tracked there.

**Comment by 0x414c49** [comment]
@rlebowitz bi-directional FlowDirection property is now supported: #59

**Comment by Eilon** [comment]
Hi @rlebowitz most missing properties have been added now, as well as several missing controls. You can build the source of this repo to see the latest, or otherwise we plan to release an update to nuget.org very soon that will have these fixes.

We have a little bit of info on how to write custom components (which can involve extending a built-in component) here: https://docs.microsoft.com/mobile-blazor-bindings/advanced/custom-components

So if you found another missing property on a built-in components, first, let us know here, but you can create a derived component that adds the missing property by following the guidance above.
