### ISSUE TITLE
Q: Xamarin XAML to HTML

### ISSUE THREAD

**Issue by grahamehorner** [xamarin/MobileBlazorBindings#68]
I'm loving the concepts of blazor that can be used to create mobile applications using the Xamarin native controls of the mobile platform; I was wondering if there was any view on using the same concept with the Xamarin XAML syntax rendering to HTML a true cross-platform-user-interface render anywhere ;)  

great work guys

**Comment by AhmedAbuelnour** [comment]
I was going to write the same, the concept is really amazing, what i really don't like about it, is that it doesn't accept HTML tags, like for Entry in Xamarin, i can't replace it with Input tag 

I hope they only depend on the HTML tags instead of the Xaml tags.

**Comment by Suriman** [comment]
This is the same request as #54. ;-)

**Comment by smartprogrammer93** [comment]
This a very horrible idea in my opinion. Using html tags instead of Xamarin forms controls will result in a framework that have very little capbilities and wont be able to accomplish a lot of the functionalities required to be in a modern mobile app.

**Comment by grahamehorner** [comment]
@smartprogrammer93 I think you may misunderstand I saying use the xaml xamarin markup syntax to develop the UI rendering to native xamarin controls for desktop and mobile and for web render to HTML modern HTML support animation and styling and in theory blazor rendering xaml to html version of xamarin controls or xamarin native is possible.

**Comment by smartprogrammer93** [comment]
@grahamehorner
From what i understood from you is you want to write xaml using xamarin forms controls and get a web ui
 you can already accomplish that using the UNO platform

**Comment by Suriman** [comment]
@smartprogrammer93 
The companies that we want to develop with XAML and deploy on the web, we don't want to develop a website with XAML, what we want is to develop a LOB (Line of Bussiness) application. These applications are much simpler, are data oriented and do not require great graphic sophistifications.

**Comment by Eilon** [comment]
I think it's fair to say there's an audience out there who would benefit from each of these ideas.

One thing we (Microsoft) are trying to figure out is: what can we build that would help the most people as soon as possible? This is of course very difficult to answer, but we are watching all these responses here and in other threads to see what people want to have as part of their dev experience with Visual Studio, C#, Azure, .NET, etc.

**Comment by GeraudFabien** [comment]
Xamarin.Form on web :
- Will help to port legacy application with ease
- Complex since there is not already a solution to display xamarin evrywhere (windows and in browser)
- Not Web compatible (If you try to debug or do some seo you can't) (Except if you find a way )

blazor tag on xamarin : 
- You get HTML/CSS/JS/WASM content to display. We can already display this kind of content on xamarin on all platform and even on windows and xamarin. The only big part would be to optimize, fix some display bug and simplify (behave like a xamarin control [Property, event, exception]).
- Debug ready (since on the web render you can exactly inspect the tree).
- May encourage framework to support blazor since it would work everywhere
- May need to hack the render a little bit to make RenderFragment (and like) work (It shouldn't be complex since we have the render done by xamarin and send back the web render. But get it light enough to work transparently would be a must)
- Not really useful for legacy application

**Comment by Eilon** [comment]
Hi everyone, it's been quite a while, so I'd like to share several updates that I think are relevant to this issue:

1. The announcement of [.NET MAUI](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/), Microsoft's official cross-platform UI system, planned for 2021. The plan is that Mobile Blazor Bindings will eventually move away from the Xamarin.Forms platform and move to .NET MAUI (which shares the same roots). You can follow .NET MAUI here: https://github.com/dotnet/maui.
   * If you're looking to build a cross-platform app that can also render to HTML, .NET MAUI would be the place to have that discussion. Mobile Blazor Binding is mostly focused on _how_ you write the app, and not as much on _where_ it runs (outside of having templates, and some platform-specific APIs).
1. New support for Hybrid Apps in Mobile Blazor Bindings Preview 4, announced today: https://devblogs.microsoft.com/aspnet/hybrid-blazor-apps-in-mobile-blazor-bindings-july-update/
   * If you're looking to build a cross-platform app using HTML as the UI rendering tech, please check out this preview! You can learn a bit more here: https://github.com/xamarin/MobileBlazorBindings/issues/121
