### ISSUE TITLE
Xamarin.Forms for Android 8.0 (API 26)?

### ISSUE THREAD

**Issue by tleylan** [xamarin/MobileBlazorBindings#83]
Quick question to see if targeting Android 8.0 is possible? I see lots of old versions available but a) don't know if they would work and b) can't quite tell which of them was used with 8.0

**Comment by Eilon** [comment]
Hi @tleylan I haven't tried Android 8.0 specifically but as far as I know it should work fine.

I think the main thing is to go to the Android project properties in your solution and select the right target:

![image](https://user-images.githubusercontent.com/202643/74054393-d375ff80-4992-11ea-883f-b1e9da58f7fc.png)

**Comment by tleylan** [comment]
I believe there is a minimum version to support the current version of Xamarin.Forms which is why I was trying to locate an older version that did support 8.0

The $(TargetFrameworkVersion) for MyApp.Android (v8.0) is less than the minimum required $(TargetFrameworkVersion) for Xamarin.Forms (8.1). You need to increase the $(TargetFrameworkVersion) for MyApp.Android.	MyApp.Android

**Comment by tleylan** [comment]
If I'm reading things correctly the MobileBlazorBindings has a dependency Xamarin.Forms (>= 4.3.0.908675) and that version of Xamarin.Forms (it seems) requires 8.1 at a minimum.

**Comment by Eilon** [comment]
Ah interesting, I'm not super familiar with how these minimums work. I'll ask some colleagues for an assist on this one.

**Comment by Eilon** [comment]
OK I talked to some Xamarin.Forms experts and here's what I got from them:

1. You can run on _much_ older Android devices than what you're even asking for. Like much older.
1. The minimum supported Android _target_ is API Level 28, but that's OK because:
   1. That's the minimum required to even push to the Google Play Store
   1. That's not the minimum _device_ you run on, it's more like the SDK you're using to build
1. Separate from the _target_ you also specify the minimum supported device, where you can go down to a really old version <-- this is likely the main source of confusion that I had
1. To guarantee that your code will work on older devices, though, you'll have to test on those (using physical device or emulator). If you want to optionally call a new API on a newer device you can do a runtime check such as [this](https://github.com/xamarin/Xamarin.Forms/blob/7a52542d50797ccc69ae1d8dd84259190d96bdb4/Xamarin.Forms.Platform.Android/Renderers/SliderRenderer.cs#L89)
1. You can find a lot more info here: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/android-api-levels?tabs=windows

**Comment by tleylan** [comment]
Well that helped I left the compile version at 10.0 and set the minimum and target to API 25 (turns out I needed that version). And... my Xamarin.Forms/Blazor app loaded and ran on my Oculus Quest. The hello world and counter works fine (font is small) and my tic-tac-toe game has some issues with the display but that tabs work.

I was determined to see something appear. I may be the first to have Blazor on the Quest. :-)

**Comment by Eilon** [comment]
Wow very cool!!! Blazor running in 3D??? 😁

**Comment by Eilon** [comment]
Closing this issue because I think everything was answered.
