### ISSUE TITLE
Binding not updating correctly to parent components

### ISSUE THREAD

**Issue by Alby-o** [xamarin/MobileBlazorBindings#88]
I followed the tutorial for the [todo app](https://docs.microsoft.com/en-us/mobile-blazor-bindings/walkthroughs/todo-app) and tried experimenting with it. When I added a summation of incomplete todos to the TodoApp component, it would update and display the correct number if the Entry or Button were interacted with. However, toggling the Switch on the TodoItemDisplay component would not correctly update the Label text.

**TodoItem.razor**
```razor
<ContentPage>
    <ContentView>
        <StackLayout Margin="new Thickness(20)">

            @* Incomplete todo count: This does not update correctly when toggling the switch on the TodoItemDisplay *@
            <Label Text="@("Todo: " + items.Count(todo => !todo.IsDone))" />

            <StackLayout Margin="new Thickness(20)" Orientation="StackOrientation.Horizontal">
                <Entry @bind-Text="newItemText" HorizontalOptions="LayoutOptions.FillAndExpand" />
                <Button Text="Add" OnClick="OnAddItem" />
            </StackLayout>

            @foreach (var item in items)
            {
                <TodoItemDisplay Item="item" />
            }
        </StackLayout>
    </ContentView>
</ContentPage>

@code
{
    string newItemText;

    List<TodoItem> items = new List<TodoItem>();

    void OnAddItem()
    {
        var newTodoItem = new TodoItem
        {
            Text = newItemText,
        };

        items.Add(newTodoItem);

        // Clear out the text in the Entry textbox
        newItemText = string.Empty;
    }
}
```

**TodoItemDisplay.razor**
```razor
<StackLayout Margin="new Thickness(20)" Orientation="StackOrientation.Horizontal">
    <Switch @bind-IsToggled="Item.IsDone"/>
    <Label Text="@Item.Text"
           TextDecorations="(Item.IsDone ? TextDecorations.Strikethrough : TextDecorations.None)"
           HorizontalOptions="LayoutOptions.FillAndExpand"
           />
</StackLayout>

@code {
    [Parameter]
    public TodoItem Item { get; set; }
}
```

**TodoItem.cs**
```cs
namespace FirstMobileBlazorBindingsApp
{
    public class TodoItem
    {
        public string Text { get; set; }
        public bool IsDone { get; set; }
    }
}
```

However, avoiding a child TodoItemDisplay component does not have the same issue:
```razor
<ContentPage>
    <ContentView>
        <StackLayout Margin="new Thickness(20)">

            <Label Text="@("Todo: " + items.Count(todo => !todo.IsDone))" />

            <StackLayout Margin="new Thickness(20)" Orientation="StackOrientation.Horizontal">
                <Entry @bind-Text="newItemText" HorizontalOptions="LayoutOptions.FillAndExpand" />
                <Button Text="Add" OnClick="OnAddItem" />
            </StackLayout>

            @foreach (var item in items)
            {
                @* Creating the components this way will correctly update the label when toggling the switch *@
                <StackLayout Margin="new Thickness(20)" Orientation="StackOrientation.Horizontal">
                    <Switch @bind-IsToggled="item.IsDone" />
                    <Label Text="@item.Text"
                           TextDecorations="(item.IsDone ? TextDecorations.Strikethrough : TextDecorations.None)"
                           HorizontalOptions="LayoutOptions.FillAndExpand" />
                </StackLayout>
            }
        </StackLayout>
    </ContentView>
</ContentPage>

@code
{
    string newItemText;

    List<TodoItem> items = new List<TodoItem>();

    void OnAddItem()
    {
        if (string.IsNullOrWhiteSpace(newItemText))
        {
            return;
        }

        var newTodoItem = new TodoItem
        {
            Text = newItemText,
        };

        items.Add(newTodoItem);

        // Clear out the text in the Entry textbox
        newItemText = string.Empty;
    }
}
```

This is using MobileBlazorBinding 0.2.42-preview

**Comment by Eilon** [comment]
Hi @Alby-o , this scenario can be a tiny bit tricky, but I hope will make sense. The key thing going on here is that Blazor doesn't always automatically know which components need to be updated and re-rendered. In this particular case, it isn't aware that the Label with the # of items complete needs to be re-rendered and updated.

The typical solution to this is to have a mechanism that lets Blazor know that something has changed and tell it to re-render yourself by calling `StateHasChanged()` in that component, which is a built-in Blazor API.

The [full Todo App sample](https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo) demonstrates this mechanism, but I'll point out the key parts:

1. Instead of binding the `Switch`'s `IsToggled` property with a two-way binding directly to the `TodoItem.IsDone` property, it is bound to an intermediate property that raises some kind of change notification.
   * Code is here: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoEntry.razor#L4
   * In this sample there's a SQLite database, but the key thing to note here is that when the item is modified and saved, it will raise an app-defined event called `AppState.OnChange`
1. In the outer list that needs to be updated, the `AppState.OnChange` event is hooked up to a method that re-renders the component:
   * Event hookup: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoList.razor#L59
   * When event is raised, call StateHasChanged: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoList.razor#L81-L83
1. The `AppState` is a global-ish state object that contains the app's state and is available to all Blazor pages that use it via dependency injection (DI)
   * AppState class defined here: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/AppState.cs
   * Registered in DI in App.cs here: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/App.cs#L27
   * And any Blazor page can consume it with the `@inject` directive like this: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/MobileBlazorBindingsTodoSample/MobileBlazorBindingsTodo/TodoEntry.razor#L1
   * More info on DI here: https://docs.microsoft.com/mobile-blazor-bindings/advanced/dependency-injection

Hopefully this makes a bit of sense and is enough to get you going. Please let me know if you have more questions on this and I'd be happy to help!

**Comment by Alby-o** [comment]
Thanks for the quick reply @Eilon ! This has helped a lot

**Comment by Eilon** [comment]
@Alby-o I'm glad it helped! Thank you for checking out Mobile Blazor Bindings and providing valuable feedback!
